version : '3.8'

services:
  django:
    container_name : django
    build: 
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - "./bs_draft_app:/bs_draft_app"
    restart: unless-stopped
    ports:
      - 8001:8000
      - 3000:3000
      - "5678:5678"  # Debug port for debugpy
    command: "python3 -m debugpy --listen 0.0.0.0:5678 --wait-for-client manage.py runserver 0.0.0.0:8000"  # Single string without `>`

    environment:
      - DEBUGPY_DJANGO=true
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:15.7-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=marcin
      - POSTGRES_PASSWORD=otyhaker
      - POSTGRES_DB=power_draft
      
  cron:
    container_name: cron
    build: 
      context: .
      dockerfile: Dockerfile-dev
    env_file:
    - .env.dev
    environment:
      - CRON=true
    depends_on:
    - db
    command:  crond -f -l 2 # Keeps the container running

volumes:
  postgres-data:
