version : '3.8'

services:

  django:
    container_name : django
    build: 
      context: ./bs_draft_app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./bs_draft_app:/usr/src/app/
    restart: unless-stopped
    ports:
      - 8001:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:15.7-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=marcin
      - POSTGRES_PASSWORD=otyhaker
      - POSTGRES_DB=power_draft
  
  cron:
    container_name: cron
    build: 
      context: ./bs_draft_app
    env_file:
    - .env.dev
    depends_on:
    - db
    command: crond -f  # as a long-running foreground process

volumes:
  postgres-data:
