FROM python:3.12-alpine
LABEL maintainer="milczanowski.marcin01@gmail.com"

ENV PYTHONUNBUFFERED 1


WORKDIR /bs_draft_app

#creating directory for the app
COPY ./requirements.txt /bs_draft_app
COPY ./bs_draft_app .
COPY ./scripts /scripts/



EXPOSE 8000
#crontab stuff
RUN apk add --update apk-cron && rm -rf /var/cache/apk/*
ADD crontab.txt /crontab.txt
RUN chmod 755 /scripts/update_db.sh
RUN /usr/bin/crontab /crontab.txt

#build fails without this stuff wheels aint spinnin
RUN apk add --no-cache --virtual .build-deps \
    ca-certificates gcc postgresql-dev linux-headers musl-dev \
    libffi-dev jpeg-dev zlib-dev 
#reqs
RUN pip install -r requirements.txt 

# Wizardry script from some article made by the only person in the world who knows alpine commands well. 

RUN find /usr/local \
        \( -type d -a -name test -o -name tests \) \
        -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) \
        -exec rm -rf '{}' + \
    && runDeps="$( \
        scanelf --needed --nobanner --recursive /usr/local \
                | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
                | sort -u \
                | xargs -r apk info --installed \
                | sort -u \
    )" \
    && apk add --virtual .rundeps $runDeps

RUN apk del .build-deps 

RUN chmod 755 /scripts/entrypoint.sh

ENV PATH="/scripts:/py/bin:$PATH"


ENTRYPOINT ["entrypoint.sh"]

