version : '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis

  django:
    container_name : django
    build: 
      context: ./bs_draft_app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./bs_draft_app:/usr/src/app/
    ports:
      - 8001:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  celery:
    container_name : celery
    build: 
      context: ./bs_draft_app
    volumes:
      - ./bs_draft_app:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
    command: celery --app=power_draft worker -l INFO 

  celery-beat:
    build: 
      context: ./bs_draft_app
    command: celery -A power_draft beat -l info
    volumes:
      - ./bs_draft_app:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - db

  db:
    container_name: postgres
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=marcin
      - POSTGRES_PASSWORD=otyhaker
      - POSTGRES_DB=power_draft
  
volumes:
  postgres-data:
