version : '3.8'

services:
  django:
    container_name : django
    build: 
      context: ./bs_draft_app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./bs_draft_app:/usr/src/app/
    ports:
      - 8001:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=marcin
      - POSTGRES_PASSWORD=otyhaker
      - POSTGRES_DB=power_draft
volumes:
  postgres-data: