services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile-prod
    restart: always
    volumes:
      - static-data:/vol/web
    env_file:
      - ./.env
    environment:
      - DJANGO=true
      - DJANGO_ALLOWED_HOSTS = ${DOMAIN}
    depends_on:
      - db

  cron:
    container_name: cron
    build:
      context: .
      dockerfile: Dockerfile-prod

    env_file:
      - ./.env
    environment:
      - CRON=true
    depends_on:
    - db
    user: bs_draft_app
    command: crond -f -l 2  # Keeps the container running

  db:
    container_name: postgres    
    image: postgres:15.7-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  proxy:
    container_name: proxy
    build:
      context: ./docker/proxy
      args:
        ENV: ${ENV}  #these are needed during buildingz        
    restart: always
    depends_on:
      - django
    ports:
      - 80:80
      - 443:443
    volumes:
      - certbot-web:/vol/www
      - proxy-dhparams:/vol/proxy
      - certbot-certs:/etc/letsencrypt
    environment:
      - DOMAIN=${DOMAIN}

  certbot:
    build:
      context: ./docker/certbot
    command: echo "Skipping..."
    environment:
      - EMAIL=${ACME_DEFAULT_EMAIL}
      - DOMAIN=${DOMAIN}
    volumes:
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt/
    depends_on:
      - proxy

volumes:
  certbot-web:
  proxy-dhparams:
  certbot-certs: