FROM python:3.12-alpine AS builder 
LABEL maintainer="milczanowski.marcin01@gmail.com"

ENV PYTHONUNBUFFERED 1
WORKDIR /bs_draft_app


COPY ./requirements.txt /bs_draft_app/requirements.txt

RUN python -m venv /py && \
    /py/bin/pip install --upgrade pip && \
    apk add --update --no-cache --virtual .build-deps \
        build-base \
        postgresql-dev \
        musl-dev \
        linux-headers && \
    apk add --update --no-cache postgresql-client busybox-suid&& \
    /py/bin/pip install -r /bs_draft_app/requirements.txt && \
    runDeps="$( \
        scanelf --needed --nobanner --recursive /py \
        | awk '{ gsub(/,/, "\\nso:", $2); print "so:" $2 }' \
        | sort -u \
        | xargs -r apk info --installed \
        | sort -u \
    )" && \
    apk add --no-cache --virtual .rundeps $runDeps && \
    apk del .build-deps

FROM python:3.12-alpine

WORKDIR /bs_draft_app
COPY --from=builder /py /py
COPY ./bs_draft_app /bs_draft_app
COPY ./scripts /scripts

EXPOSE 8000
#cron stuff and creating user&group bs_draft_app
ADD crontab.txt /etc/crontabs/bs_draft_app
RUN apk add --update apk-cron && rm -rf /var/cache/apk/* 
RUN chmod 755 /scripts/update_db.sh
RUN chmod u+s /usr/bin/crontab && \
    adduser --disabled-password --no-create-home bs_draft_app && \
    apk add --update --no-cache busybox-suid && \
    apk add --update apk-cron && \
    chown bs_draft_app:bs_draft_app /etc/crontabs/bs_draft_app && \
    chmod 600 /etc/crontabs/bs_draft_app && \
#the rest    
    apk add --update --no-cache postgresql-client&& \
    mkdir -p /vol/web/static && \
    chown -R bs_draft_app:bs_draft_app /vol && \
    chmod -R 755 /vol && \
    chmod -R +x /scripts &&\
#optimize space, articles are op
    find /usr/local \
\( -type d -a -name test -o -name tests \) \
-o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) \
-exec rm -rf '{}' + \
&& runDeps="$( \
scanelf --needed --nobanner --recursive /usr/local \
        | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
        | sort -u \
        | xargs -r apk info --installed \
        | sort -u \
)" \
&& apk add --virtual .rundeps $runDeps


ENV PATH="/scripts:/py/bin:$PATH"

ENV PATH="/bs_draft_app:/py/bin:$PATH"

USER bs_draft_app

ENTRYPOINT ["entrypoint.sh"]

CMD ["run.sh"]