# Generated by Django 4.1.3 on 2024-08-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedData',
            fields=[
                ('last_player_checked', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('scanned_games', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'ScannedData',
            },
        ),
        migrations.DeleteModel(
            name='LastPlayerChecked',
        ),
        migrations.AlterModelOptions(
            name='map',
            options={'ordering': ('games_played',)},
        ),
    ]
