# Generated by Django 4.1.3 on 2024-11-22 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('matches_won', models.PositiveIntegerField(default=0)),
                ('win_rate_together', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'Synergies',
            },
        ),
        migrations.RemoveIndex(
            model_name='headtohead',
            name='picks_manag_brawler_d7e664_idx',
        ),
        migrations.RemoveIndex(
            model_name='headtohead',
            name='picks_manag_map_id_cd023a_idx',
        ),
        migrations.AddField(
            model_name='synergy',
            name='brawler_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synergy_a', to='picks_manager.brawler'),
        ),
        migrations.AddField(
            model_name='synergy',
            name='brawler_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synergy_b', to='picks_manager.brawler'),
        ),
        migrations.AddField(
            model_name='synergy',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picks_manager.map'),
        ),
        migrations.AlterUniqueTogether(
            name='synergy',
            unique_together={('brawler_a', 'brawler_b', 'map')},
        ),
    ]
