# Generated by Django 5.1.4 on 2024-12-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0002_synergy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headtohead',
            old_name='map',
            new_name='map_name',
        ),
        migrations.AlterUniqueTogether(
            name='headtohead',
            unique_together={('brawler_a', 'brawler_b', 'map_name')},
        ),
    ]
