# Generated by Django 4.1.3 on 2024-08-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0002_scanneddata_delete_lastplayerchecked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brawler',
            name='countered_by_pets',
            field=models.CharField(default='no', max_length=6),
        ),
        migrations.AddField(
            model_name='brawler',
            name='counters_pets',
            field=models.CharField(default='no', max_length=6),
        ),
        migrations.AddField(
            model_name='brawler',
            name='easy_to_counter',
            field=models.CharField(default='no', max_length=6),
        ),
        migrations.AddField(
            model_name='brawler',
            name='has_pets',
            field=models.CharField(default='no', max_length=6),
        ),
    ]
