# Generated by Django 5.1.4 on 2025-01-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0003_rename_map_headtohead_map_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brawler',
            name='counterabilty',
            field=models.FloatField(default=0.0),
        ),
    ]
