# Generated by Django 4.1.3 on 2024-08-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0003_brawler_countered_by_pets_brawler_counters_pets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brawler',
            name='gem_carrier',
            field=models.CharField(default='no', max_length=6),
        ),
        migrations.AddField(
            model_name='brawler',
            name='hz_sitter',
            field=models.CharField(default='no', max_length=6),
        ),
    ]
