# Generated by Django 4.1.3 on 2024-09-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0004_brawler_gem_carrier_brawler_hz_sitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanneddata',
            name='ammount_of_maps',
            field=models.IntegerField(default=18),
        ),
    ]
