# Generated by Django 5.1.4 on 2025-02-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0004_brawler_counterabilty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brawler',
            old_name='counterabilty',
            new_name='counterability',
        ),
    ]
