# Generated by Django 5.1.4 on 2025-02-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0005_rename_counterabilty_brawler_counterability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brawler',
            name='counterability',
        ),
        migrations.AddField(
            model_name='winrate',
            name='counterability',
            field=models.FloatField(default=0.0),
        ),
    ]
