# Generated by Django 4.1.3 on 2024-04-16 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brawler_Class',
            new_name='BrawlerClass',
        ),
        migrations.AlterModelOptions(
            name='brawlerclass',
            options={'verbose_name_plural': 'Brawler classes'},
        ),
    ]
