# Generated by Django 4.1.3 on 2024-03-05 21:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('use_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('games_played', models.IntegerField()),
                ('games_won', models.IntegerField()),
                ('brawler_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picks_manager.brawler')),
                ('map_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picks_manager.map')),
            ],
            options={
                'unique_together': {('brawler_name', 'map_name')},
            },
        ),
    ]
