# Generated by Django 4.1.3 on 2024-02-23 13:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brawlers',
            fields=[
                ('brawler_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('rarity', models.CharField(choices=[('LEGENDARY', 'Legendaru'), ('MYTHICAL', 'Mythical'), ('EPIC', 'Epic'), ('SUPER RARE', 'Super rare'), ('RARE', 'Rare')], default='RARE', max_length=11)),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Modes',
            fields=[
                ('mode_name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('mode_icon', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='maplist',
            name='mode_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picks_manager.modes'),
        ),
        migrations.CreateModel(
            name='WinRate',
            fields=[
                ('brawler_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='picks_manager.brawlers')),
                ('win_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('use_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('map_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picks_manager.maplist')),
            ],
            options={
                'unique_together': {('brawler_name', 'map_name')},
            },
        ),
    ]
