# Generated by Django 4.1.3 on 2024-03-12 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0002_winrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winrate',
            name='use_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
