# Generated by Django 4.1.3 on 2024-04-21 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0002_rename_brawler_class_brawlerclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_checked',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
