# Generated by Django 4.1.3 on 2024-03-12 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0003_alter_winrate_use_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winrate',
            name='use_rate',
            field=models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
