# Generated by Django 4.1.3 on 2024-02-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0003_rename_maplist_maps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brawlers',
            new_name='Brawler',
        ),
        migrations.RenameModel(
            old_name='Maps',
            new_name='Map',
        ),
        migrations.RenameModel(
            old_name='Modes',
            new_name='Mode',
        ),
    ]
