# Generated by Django 4.1.3 on 2024-02-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0004_rename_brawlers_brawler_rename_maps_map_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_tag', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
