# Generated by Django 4.1.3 on 2024-03-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0005_alter_winrate_use_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode',
            name='mode_color',
            field=models.CharField(default='nothing', max_length=30),
            preserve_default=False,
        ),
    ]
