# Generated by Django 4.1.3 on 2024-03-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0005_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastPlayerChecked',
            fields=[
                ('last_player_checked', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
