# Generated by Django 4.1.3 on 2024-03-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0006_lastplayerchecked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lastplayerchecked',
            options={'verbose_name_plural': 'LastPlayerChecked'},
        ),
        migrations.AlterField(
            model_name='lastplayerchecked',
            name='last_player_checked',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
