# Generated by Django 4.1.3 on 2024-04-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0006_mode_mode_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='brawler',
            name='brawler_class',
            field=models.CharField(default='False', max_length=25),
            preserve_default=False,
        ),
    ]
