# Generated by Django 4.1.3 on 2024-03-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0007_alter_lastplayerchecked_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brawler',
            name='rarity',
            field=models.CharField(choices=[('LEGENDARY', 'Legendary'), ('MYTHICAL', 'Mythical'), ('EPIC', 'Epic'), ('SUPER RARE', 'Super rare'), ('RARE', 'Rare')], default='RARE', max_length=11),
        ),
    ]
