# Generated by Django 4.1.3 on 2024-03-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0008_alter_brawler_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='games_played',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
