# Generated by Django 4.1.3 on 2024-04-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0008_brawler_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brawler_class',
            name='countered_by',
            field=models.CharField(default='Null', max_length=25),
            preserve_default=False,
        ),
    ]
