# Generated by Django 4.1.3 on 2024-03-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0009_map_games_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='winrate',
            name='games_played',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winrate',
            name='games_won',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
