# Generated by Django 4.1.3 on 2024-03-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks_manager', '0010_winrate_games_played_winrate_games_won'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winrate',
            name='win_rate',
        ),
    ]
